negativo:
  - abandono
  - abandonada
  - abandonado
  - aflictivo
  - aflictivos
  - amenaza
  - angustia
  - angustiada
  - angustiado
  - ardua
  - arduo
  - avieso
  - bochornosa
  - bochornoso
  - cadena
  - cadenas
  - calumnia
  - calumniada
  - castigo
  - cautiva
  - cautiverio
  - censura
  - conflicto
  - contradictoria
  - corrompe
  - corromper
  - crisis
  - cruel
  - cruenta
  - daño
  - daños
  - debil
  - debiles
  - decadencia
  - decaer
  - defecto
  - derrota
  - derrotada
  - derribo
  - derrumbe
  - desamparo
  - desastroso
  - desavenencias
  - desdichada
  - desdichado
  - desden
  - desdenes
  - desfavorable
  - desligaba
  - desmoralizacion
  - desolacion
  - desgracia
  - desgraciada
  - desgraciado
  - detentado
  - dificil
  - dificultad
  - doliente
  - dolor
  - dolores
  - dolorosa
  - dura
  - duro
  - enemigo
  - enemiga
  - enemigos
  - enferma
  - enfermedad
  - enfermo
  - esclava
  - esclavitud
  - esclavo
  - esterilidad
  - estorbo
  - fatal
  - fatalidad
  - furia
  - gime
  - guerra
  - guerras
  - hastio
  - herida
  - heridas
  - ignorancia
  - ignorante
  - imperialismo
  - impuro
  - infortunio
  - ingrato
  - injusta
  - injusticia
  - injusto
  - insidia
  - lagrimas
  - lamentable
  - lamentables
  - llanto
  - mal
  - mala
  - maldad
  - males
  - malo
  - melancolia
  - melancolica
  - mentira
  - miserable
  - miseria
  - mordido
  - muerta
  - muerte
  - muerto
  - nocivo
  - nocivos
  - obstaculo
  - obstaculos
  - opresion
  - oprimida
  - oprimido
  - oscuro
  - oscura
  - padecer
  - padecimiento
  - padecimientos
  - pasiones
  - peligro
  - penas
  - perdida
  - perder
  - peso
  - pobre
  - pobres
  - pobreza
  - presion
  - problema
  - quebrantos
  - rebelde
  - rebeldia
  - recio
  - refractario
  - ruina
  - ruinas
  - servidumbre
  - sombras
  - sometida
  - sometimiento
  - sufre
  - sufrimiento
  - sufrimientos
  - sufrir
  - tirania
  - tormento
  - torturado
  - tortuosa
  - triste
  - tristeza
  - tristes
  - turbulento
  - vano
  - vicio
  - vicios
  - yugo