positivo:
  - admirable
  - admirada
  - admirado
  - agradecida
  - agradecido
  - agradecimiento
  - alegra
  - alegre
  - alegria
  - alegrias
  - aliento
  - alma
  - alborozo
  - amor
  - amado
  - amada
  - amar
  - amantes
  - amistad
  - bella
  - bellas
  - belleza
  - bello
  - bellos
  - bien
  - bienestar
  - bondad
  - bondadosa
  - bondadoso
  - calma
  - caridad
  - cariño
  - carinosa
  - carinoso
  - celebrar
  - celebramos
  - ciencia
  - ciencias
  - civilizacion
  - complacida
  - complacido
  - consuelo
  - cultura
  - culta
  - culto
  - deleite
  - deleitosa
  - delicada
  - delicadeza
  - delicado
  - desarrollo
  - despierta
  - despertar
  - dicha
  - digna
  - dignas
  - dignidad
  - digno
  - dignos
  - distinguida
  - distinguido
  - dulce
  - dulzura
  - educacion
  - eficiente
  - eficaces
  - enaltece
  - enaltecer
  - encanto
  - encantador
  - encantadora
  - engrandecimiento
  - enseñanza
  - entusiasmo
  - entusiasta
  - esperanza
  - esperanzas
  - estima
  - estimada
  - estimado
  - exquisita
  - exquisito
  - fecunda
  - fecundo
  - feliz
  - felices
  - felicidad
  - favorable
  - fraternidad
  - fraternal
  - generosa
  - generoso
  - gloria
  - gloriosa
  - glorioso
  - grata
  - grato
  - hermosa
  - hermosas
  - hermoso
  - hermosos
  - heroica
  - heroico
  - heroismo
  - honor
  - honra
  - honrosa
  - honroso
  - ilustracion
  - ilustrada
  - ilustrado
  - importante
  - inteligencia
  - inteligente
  - inteligentes
  - instruccion
  - justicia
  - justa
  - justo
  - libre
  - libres
  - libertad
  - luz
  - luces
  - luminosa
  - luminoso
  - mejor
  - mejoramiento
  - merecida
  - merecer
  - merito
  - moderna
  - moderno
  - noble
  - nobles
  - nobleza
  - pacifico
  - paz
  - porvenir
  - progreso
  - progresiva
  - progresivo
  - prosperidad
  - pura
  - puras
  - puro
  - puros
  - radiante
  - razon
  - razonable
  - recompensa
  - redencion
  - redime
  - reforma
  - robusta
  - robusto
  - sabio
  - sabia
  - saber
  - sagrada
  - sagrado
  - salud
  - saludable
  - sana
  - sano
  - serenidad
  - serena
  - sereno
  - sublime
  - superior
  - superiores
  - tranquilidad
  - triunfo
  - triunfar
  - triunfante
  - triunfos
  - util
  - utiles
  - valentia
  - valiente
  - valor
  - ventura
  - venturosa
  - venturoso
  - victoria
  - victoriosa
  - victorioso
  - vida
  - vigorosa
  - vigoroso
  - virtud
  - virtudes
  - virtuosa
  - virtuoso
  - voluntad