mujer:
  - mujer
  - mujeres
  - femenina
  - femenino
  - feminidad
  - madre
  - madres
  - esposa
  - señorita
  - dama
  - damas
  - bello sexo

feminismo:
  - feminismo
  - feminista
  - feministas
  - sufragio
  - sufragista
  - derechos de la mujer
  - emancipación
  - igualdad
  - mujer moderna

patria:
  - patria
  - patriota
  - patriótico
  - patriotismo
  - nación
  - nacional
  - independencia
  - soberanía
  - pueblo

raza:
  - raza
  - razas
  - racial
  - blanco
  - blanca
  - negro
  - negra
  - mestizo
  - mestiza
  - latina
  - latino

educacion:
  - educación
  - enseñanza
  - instrucción
  - escuela
  - colegio
  - colegios
  - cultura
  - ciencia
  - inteligencia
  - lectura

hogar:
  - hogar
  - familia
  - casa
  - doméstico
  - doméstica
  - hijos
  - hijas
  - esposo
  - esposa
  - maternidad

religion:
  - dios
  - religión
  - religiosa
  - religioso
  - católica
  - católico
  - cristiana
  - cristiano
  - moral
  - virtud

colonialismo:
  - colonial
  - colonialismo
  - imperialismo
  - intervención
  - ocupación
  - ocupante
  - soberanía
  - independencia
  - estados unidos
  - yanqui
  - autonomía