excluidos_por_ser_temas_no_polaridad:
  - mujer
  - mujeres
  - femenina
  - feminismo
  - feminista
  - patria
  - patriota
  - nacion
  - nacional
  - raza
  - razas
  - religion
  - catolica
  - catolico
  - hombre
  - hombres
  - america
  - espana
  - sufragio
  - colonialismo
  - educacion
  - hogar
  - familia

excluidos_por_ambiguedad_contextual:
  - moral
  - sacrificio
  - deber
  - autoridad
  - tradicion
  - moderna
  - moderno
  - civilizacion
  - razon
  - alma
  - santo
  - santa
  - pura
  - puro
  - sensibilidad
  - pasion
  - pasiones